#!/bin/bash
#This script is intended to accept the name of a file as a 
#parameter, and then open a window in google-chrome with that
#file. 

first=$1
second=$2
# Make sure BROWSER variable points to valid command to open browser
BROWSER="Google Chrome"

if [ "$first" == "-u" ]
then


open -a "$BROWSER" "http://$second"

elif [ -z $second ]
then

open -a "$BROWSER" "file://localhost$(pwd)/$first"


else

echo "Invalid input, please use -u flag to enter URL"
fi

exit 0



