#!/bin/bash
#This script is intended to accept the name of a file as a 
#parameter, and then open a window in google-chrome with that
#file. 

#check if previously installed, if not proceed with symlink
if [ ! -f "/usr/local/bin/chrome" ]
then
	chmod +x chrome
	ln -s "$(pwd)/chrome" /usr/local/bin/chrome
fi


first=$1
second=$2
# Make sure BROWSER variable points to valid command to open browser
BROWSER="Google Chrome"

if [ "$first" == "-u" ]
then


open -a "$BROWSER" "http://$second"

elif [ -z $second ]
then

open -a "$BROWSER" "file://localhost$(pwd)/$first"


else

echo "Invalid input, please use -u flag to enter URL"
fi

exit 0



